# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LinkMoa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift', '=10.1.4'
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'lottie-ios'
  pod 'Moya', '~> 14.0'
  # Include all other configurations except `Debug-M1`
  pod 'GoogleSignIn', :configurations => ['Debug', 'Release']
  # Pods for LinkMoa
end

target 'LinkMoaShareExtension' do
   # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift', '=10.1.4'
  pod 'Toast-Swift', '~> 5.0.1'
end

